- name: This installs zabbix
  hosts: "{{group}}"
  become: yes
  roles:
  - role: dj-wasabi.zabbix-agent
    tags: common

- name: setup haproxy
  hosts: "{{group}}_haproxy"
  become: yes
  roles:
  - role: geerlingguy.haproxy
    tags: haproxy

- name: This playbook uses a role
  hosts: "{{group}}_web"
  become: yes
  roles:
  - apache
  
